// Hand-written Section 2 questions in the TMUA style.
// o[0] is the correct option and options are shuffled when shown,
// unless `fixed` is set, in which case the order is kept and `a` is the correct index.

const NS = ['necessary but not sufficient', 'sufficient but not necessary', 'necessary and sufficient', 'neither necessary nor sufficient'];
const ns = (q, a, why) => ({ q, o: NS, fixed: true, a, why });

export const BANK = {
  implication: [
    { q: 'Which statement is true for all real x?',
      o: ['x &gt; 2 ⇒ x² &gt; 4', 'x² &gt; 4 ⇒ x &gt; 2', 'x² = 4 ⇒ x = 2', 'x &lt; 2 ⇒ x² &lt; 4'],
      why: 'If x &gt; 2 then x² &gt; 4. x = −3 is a counterexample to the second and fourth options (x² = 9 but x &lt; 2), and x = −2 is a counterexample to the third.' },
    { q: 'The statement "if P then Q" is false in exactly which case?',
      o: ['P is true and Q is false', 'P is false and Q is true', 'P is false and Q is false', 'P is true and Q is true'],
      why: 'An implication only fails when its hypothesis holds and its conclusion does not. When P is false the implication is true whatever Q is.' },
    { q: 'It is true that "if it rains, the match is cancelled". The match was not cancelled. What can be deduced?',
      o: ['It did not rain', 'It rained', 'Nothing can be deduced about the rain', 'The match will be cancelled next time it rains, but not otherwise'],
      why: 'This is the contrapositive: not cancelled ⇒ no rain. The last option adds "but not otherwise", which the statement does not say.' },
    { q: 'It is true that "if it rains, the match is cancelled". The match was cancelled. What can be deduced?',
      o: ['Nothing can be deduced about the rain', 'It rained', 'It did not rain', 'It rained, and nothing else could have cancelled the match'],
      why: 'Concluding that it rained would use the converse, which has not been given. The match could have been cancelled for another reason.' },
    { q: 'a and b are real numbers. Which implication is always true?',
      o: ['a &gt; b ⇒ a³ &gt; b³', 'a &gt; b ⇒ a² &gt; b²', 'a² &gt; b² ⇒ a &gt; b', 'ab &gt; 0 ⇒ a &gt; 0 and b &gt; 0'],
      why: 'Cubing preserves order for all reals. Counterexamples to the others: a = 1, b = −2; a = −2, b = 1; a = b = −1.' },
    { q: 'P ⇒ Q and Q ⇒ R are both true. Which of these must be true?',
      o: ['P ⇒ R', 'R ⇒ P', 'Q ⇒ P', 'not P ⇒ not R'],
      why: 'Implications chain: P ⇒ Q ⇒ R. The others are converses or inverses and need not hold.' },
    { q: 'n is a positive integer. Which statement is true?',
      o: ['If n² is even then n is even', 'If n is prime then n is odd', 'If n is a multiple of 3 then n is a multiple of 6', 'If n is odd then n is prime'],
      why: 'If n were odd, n² would be odd. Counterexamples to the others: n = 2, n = 3, n = 9.' },
  ],
  converse: [
    { q: 'n is an integer. What is the contrapositive of "if n² is odd then n is odd"?',
      o: ['If n is not odd then n² is not odd', 'If n is odd then n² is odd', 'If n² is not odd then n is not odd', 'n² is odd and n is not odd'],
      why: 'The contrapositive of P ⇒ Q is not Q ⇒ not P. The second option is the converse, the third is the inverse and the fourth is the negation.' },
    { q: 'Statement: "if a quadrilateral is a square then it has four equal sides". Which is correct?', fixed: true, a: 1,
      o: ['The statement and its converse are both true', 'The statement is true and its converse is false', 'The statement is false and its converse is true', 'The statement and its converse are both false'],
      why: 'Every square has four equal sides. The converse fails: a rhombus that is not a square has four equal sides.' },
    { q: 'Which is logically equivalent to "if x &gt; 3 then x² &gt; 9"?',
      o: ['If x² ≤ 9 then x ≤ 3', 'If x² &gt; 9 then x &gt; 3', 'If x ≤ 3 then x² ≤ 9', 'x &gt; 3 and x² ≤ 9'],
      why: 'A statement is equivalent to its contrapositive. The second is the converse, the third the inverse, the fourth the negation.' },
    { q: 'S: "if a triangle is equilateral then it is isosceles" is true. Consider<br>I: if a triangle is isosceles then it is equilateral<br>II: if a triangle is not isosceles then it is not equilateral<br>III: if a triangle is not equilateral then it is not isosceles<br>Which must be true because S is true?', fixed: true, a: 1,
      o: ['I only', 'II only', 'I and II only', 'II and III only', 'I, II and III'],
      why: 'II is the contrapositive of S, so it is equivalent to S. I is the converse and III is the inverse; neither follows from S.' },
    { q: 'The converse of P ⇒ Q is logically equivalent to which of these?',
      o: ['not P ⇒ not Q', 'not Q ⇒ not P', 'P ⇒ Q', 'P and not Q'],
      why: 'The converse is Q ⇒ P, and its contrapositive is not P ⇒ not Q (the inverse of the original).' },
    { q: 'a and b are integers. What is the contrapositive of "if ab is even then a is even or b is even"?',
      o: ['If a is odd and b is odd then ab is odd', 'If a is odd or b is odd then ab is odd', 'If a is even or b is even then ab is even', 'If ab is odd then a is odd and b is odd'],
      why: 'Negate and swap. The negation of "a is even or b is even" is "a is odd and b is odd".' },
  ],
  necsuff: [
    ns('x is real. The condition x &gt; 2 is ___ for x² &gt; 4.', 1, 'x &gt; 2 guarantees x² &gt; 4, so it is sufficient. It is not necessary: x = −3 also has x² &gt; 4.'),
    ns('A quadrilateral "has four right angles". This condition is ___ for it to be a square.', 0, 'Every square has four right angles, so it is necessary. A non-square rectangle shows it is not sufficient.'),
    ns('x is real. The condition x² = x is ___ for x = 1.', 0, 'x = 1 gives x² = x, so it is necessary. It is not sufficient because x = 0 also satisfies x² = x.'),
    ns('A triangle has sides a ≤ b ≤ c. The condition a² + b² = c² is ___ for the triangle to be right-angled.', 2, 'Pythagoras gives one direction and its converse the other, so the conditions are equivalent.'),
    ns('x is real. The condition x &gt; 0 is ___ for x² &gt; 1.', 3, 'Not sufficient: x = 1/2. Not necessary: x = −2.'),
    ns('b and c are real. The condition c &lt; 0 is ___ for x² + bx + c = 0 to have two distinct real roots.', 1, 'If c &lt; 0 then b² − 4c &gt; 0, so it is sufficient. It is not necessary: x² − 3x + 2 = 0 has two distinct roots with c &gt; 0.'),
    ns('x is real. The condition x &lt; 1 is ___ for x² &lt; 1.', 0, 'x² &lt; 1 means −1 &lt; x &lt; 1, which forces x &lt; 1, so it is necessary. x = −2 shows it is not sufficient.'),
    { q: '"P is necessary for Q" means which of these?',
      o: ['Q ⇒ P', 'P ⇒ Q', 'P ⇔ Q', 'not Q ⇒ not P'],
      why: 'Necessary means Q cannot hold without P, that is Q ⇒ P. "P ⇒ Q" and its contrapositive "not Q ⇒ not P" both say P is sufficient.' },
  ],
  quantifiers: [
    { q: 'What is the negation of "all prime numbers are odd"?',
      o: ['There is a prime number that is not odd', 'No prime numbers are odd', 'All prime numbers are even', 'There is a prime number that is odd'],
      why: 'The negation of "for all x, P(x)" is "there exists x with not P(x)".' },
    { q: 'What is the negation of "there exists a real x such that x² &lt; 0"?',
      o: ['For all real x, x² ≥ 0', 'For all real x, x² &lt; 0', 'There exists a real x such that x² ≥ 0', 'There exists a real x such that x² &gt; 0'],
      why: 'Swap "there exists" for "for all" and negate the condition: not (x² &lt; 0) is x² ≥ 0.' },
    { q: 'What is the negation of "for every integer n there exists an integer m with m &gt; n"?',
      o: ['There exists an integer n such that for all integers m, m ≤ n', 'For every integer n there exists an integer m with m ≤ n', 'There exist integers n and m with m ≤ n', 'For every integer n and every integer m, m ≤ n'],
      why: 'Work from the outside in: each "for every" becomes "there exists" and vice versa, then the final condition is negated.' },
    { q: 'What is the negation of "x &gt; 0 and y &gt; 0"?',
      o: ['x ≤ 0 or y ≤ 0', 'x ≤ 0 and y ≤ 0', 'x &lt; 0 or y &lt; 0', 'x &lt; 0 and y &lt; 0'],
      why: 'Negating "A and B" gives "not A or not B", and not (x &gt; 0) is x ≤ 0.' },
    { q: 'x and y are real. Which statement is true?',
      o: ['For all x there exists y such that y³ = x', 'For all x there exists y such that y² = x', 'There exists y such that for all x, y &gt; x', 'There exists x such that for all y, xy = 1'],
      why: 'Every real number has a real cube root. The others fail: negative x has no real square root; no real number exceeds all others (take x = y); xy = 1 fails at y = 0.' },
    { q: 'For a particular integer n, what is the negation of "if n is prime then n is odd"?',
      o: ['n is prime and n is not odd', 'If n is prime then n is not odd', 'If n is not prime then n is not odd', 'n is not prime and n is odd'],
      why: 'P ⇒ Q is false only when P is true and Q is false, so its negation is "P and not Q".' },
    { q: 'What is enough to disprove "for all positive integers n, n² + n + 41 is prime"?',
      o: ['Finding one n for which n² + n + 41 is not prime', 'Checking that it is prime for n = 1 to 10', 'Finding one n for which n² + n + 41 is prime', 'Showing that it is not prime for every n'],
      why: 'A single counterexample disproves a "for all" statement. Here n = 40 gives 1681 = 41².' },
  ],
  proof: [
    { q: 'To show √2 is irrational, a student assumes √2 = a/b in lowest terms and deduces that a and b are both even. What type of proof is this?',
      o: ['Proof by contradiction', 'Direct proof (deduction)', 'Proof by exhaustion', 'Disproof by counterexample'],
      why: 'The student assumes the opposite of the claim and reaches an impossibility (a fraction in lowest terms with both parts even).' },
    { q: 'To show n² + n is even for every integer n, a student treats "n even" and "n odd" separately. What type of proof is this?',
      o: ['Proof by exhaustion', 'Proof by contradiction', 'Disproof by counterexample', 'Proof by contrapositive'],
      why: 'The cases n even and n odd cover every integer, and the claim is checked in each case.' },
    { q: 'Which value of n is a counterexample to "if n is a positive integer then 2ⁿ − 1 is prime"?', fixed: true, a: 2,
      o: ['n = 2', 'n = 3', 'n = 4', 'n = 5', 'n = 7'],
      why: '2⁴ − 1 = 15 = 3 × 5. The other values give 3, 7, 31 and 127, which are all prime.' },
    { q: 'Which value of x is a counterexample to "for all real x, x² ≥ x"?', fixed: true, a: 2,
      o: ['x = −1', 'x = 0', 'x = 1/2', 'x = 2'],
      why: '(1/2)² = 1/4, which is less than 1/2. The statement fails exactly for 0 &lt; x &lt; 1.' },
    { q: 'To prove "if n² is even then n is even", a student proves "if n is odd then n² is odd" (n an integer). Why is this valid?',
      o: ['The second statement is the contrapositive of the first, and they are equivalent', 'The second statement is the converse of the first, and they are equivalent', 'It gives a counterexample to the negation', 'It is not valid; the first statement is still unproved'],
      why: 'For integers "not even" is "odd", so the second statement is not Q ⇒ not P, the contrapositive.' },
    { q: 'To show the sum of three consecutive integers is divisible by 3, a student writes them as n, n + 1, n + 2 and shows the sum is 3(n + 1). What type of proof is this?',
      o: ['Direct proof (deduction)', 'Proof by exhaustion', 'Proof by contradiction', 'Disproof by counterexample'],
      why: 'The result is deduced directly from a general algebraic form, with no cases and no assumption of the opposite.' },
    { q: 'Which shape is a counterexample to "if a quadrilateral has perpendicular diagonals then it is a rhombus"?',
      o: ['A kite with two different side lengths', 'A square', 'A rectangle that is not a square', 'A parallelogram whose diagonals are not perpendicular'],
      why: 'A counterexample must satisfy the hypothesis and fail the conclusion. Such a kite has perpendicular diagonals but is not a rhombus. The rectangle and parallelogram do not satisfy the hypothesis; the square satisfies the conclusion.' },
  ],
  errors: [
    { q: 'A student solves x² = 3x:<br>(1) Divide both sides by x: x = 3<br>(2) So the only solution is x = 3.<br>What is wrong?',
      o: ['Dividing by x is not valid when x = 0, so the solution x = 0 is lost', 'x = 3 does not satisfy the equation', 'Both sides should be square rooted first', 'Nothing; the argument is correct'],
      why: 'x² − 3x = x(x − 3) = 0 gives x = 0 or x = 3. Division by x silently assumes x ≠ 0.' },
    { q: 'A student solves √(x + 2) = x:<br>(I) x + 2 = x²<br>(II) x² − x − 2 = 0<br>(III) (x − 2)(x + 1) = 0<br>(IV) so x = 2 or x = −1.<br>What is wrong?',
      o: ['Squaring is not reversible, so x = −1 must be checked and rejected', 'The factorisation in step III is incorrect', 'x = 2 does not satisfy the original equation', 'Step II has a sign error'],
      why: 'Each step follows from the one before, but (I) does not imply the original equation. x = −1 gives √1 = 1, not −1.' },
    { q: 'Claim: for non-zero real a and b, if a &gt; b then 1/a &lt; 1/b.<br>"Proof": divide both sides of a &gt; b by ab to get 1/b &gt; 1/a.<br>What is wrong?',
      o: ['Dividing by ab reverses the inequality when ab is negative', 'Dividing by ab always reverses the inequality', 'Nothing; the claim is true and the proof is correct', 'The proof should divide by a + b instead'],
      why: 'The step is only valid when ab &gt; 0. Counterexample to the claim: a = 1, b = −1.' },
    { q: 'A "proof" that 2 = 1:<br>(1) Let a = b<br>(2) a² = ab<br>(3) a² − b² = ab − b²<br>(4) (a − b)(a + b) = b(a − b)<br>(5) a + b = b<br>(6) 2b = b<br>(7) 2 = 1<br>Which is the first invalid step?', fixed: true, a: 2,
      o: ['Step 3', 'Step 4', 'Step 5', 'Step 7'],
      why: 'Step 5 divides both sides by a − b, which is zero because a = b. Steps 2 to 4 are all valid.' },
    { q: 'A student solves (x − 1)/(x + 2) &gt; 0 by multiplying both sides by (x + 2) to get x − 1 &gt; 0, so x &gt; 1. What is wrong?',
      o: ['x + 2 may be negative, which reverses the inequality; the solutions x &lt; −2 are missed', 'x &gt; 1 does not satisfy the inequality', 'Both sides should have been multiplied by (x − 1)', 'Nothing; the argument is correct'],
      why: 'The fraction is positive when top and bottom have the same sign: x &gt; 1 or x &lt; −2. Multiplying by (x + 2)² avoids the problem.' },
    { q: 'A student writes: "sin x = sin y, therefore x = y". What is wrong?',
      o: ['Different inputs can give the same sine, for example 30° and 150°', 'sin x = sin y is only possible when x = y = 0', 'The conclusion should be x = −y', 'Nothing; the argument is correct'],
      why: 'f(x) = f(y) only forces x = y when f is one-to-one. Sine is not: sin 30° = sin 150° = 1/2.' },
    { q: 'A student checks that n² − n + 11 is prime for n = 1, 2, ..., 10 and concludes it is prime for every positive integer n. What is wrong?',
      o: ['Checking finitely many cases cannot prove a statement about all n; n = 11 gives 121', 'The value at n = 5 is not prime', 'The student should have started from n = 0', 'Nothing; ten cases is enough to establish the pattern'],
      why: 'A "for all" statement needs a general argument. Here n = 11 gives 121 = 11², a counterexample.' },
  ],
};
